### PR TITLE
Add cronjob parameter chainability

### LINKED ISSUE #9: Chainable Cronjob parameters
As for now, different cronjob parameters are exposed as properties (`$minutes`, `$hours` and so on).  
What I propose is to implement getters and setters for those so you could write something like this (rewriting the example from Readme):

```php
$crontabJob = new CrontabJob();
$crontabJob->setMinutes(30)->setHours(23)->setDayOfMonth('*')->setMonths('*')->setDayOfWeek('*')->setTaskCommandLine('df >> /tmp/df.log')->setComments('Logging disk usage');
```

Seems a bit more concise, no? :)  
If you have nothing against it, I'd implement this and send a PR. Thanks!

### PR DESCRIPTION
**Pull request by Menelion**
Fixes #9. Made the following changes:

- Added getters and setters for better OOP paradigm and parameters chainability
- In setters added some validation rules. Note: not everything is implemented yet, should be discussed (for example, months and days abbreviations are not validated)
- Changed tests and added new tests accordingly
- Fixed some spelling errors in English, including in method names (only in the tests!)
- Changed Readme to reflect new functionality
- The new functionality should not break anything, if it does, please chime in.

### CODE REVIEW

**Comment by TiBeN** [comment]
Hi Menelion,

Thank you very much for such a great contribution. Everything is ok for me, i have just a style request:
I try more and more in my code project to reduce the number of chars per lines (the good old 80 chars rule). I think theses lines:
```
$crontabJob->setMinutes(30)->setHours(23)->setDayOfMonth('*')->setMonths('*')->setDayOfWeek('*')->setTaskCommandLine('df >> /tmp/df.log')->setComments('Logging disk usage'); // Comments are persisted in the crontab
```

could be rewritten like this:


    $crontabJob
        ->setMinutes(30)
        ->setHours(23)
        ->setDayOfMonth('*')
        ->setMonths('*')
        ->setDayOfWeek('*')
        ->setTaskCommandLine('df >> /tmp/df.log')
        ->setComments('Logging disk usage'); // Comments are persisted in the crontab

or variant


    $crontabJob
        ->setMinutes(30)
        ->setHours(23)
        ->setDayOfMonth('*')
        ->setMonths('*')
        ->setDayOfWeek('*')
        ->setTaskCommandLine('df >> /tmp/df.log')
        ->setComments('Logging disk usage') // Comments are persisted in the crontab
    ;

It is easier to read (i find) and fluent interfaces are commonly presented like this. You can change your pull request by yourself or, if you prefer, i merge this one and do the changes afterwards.

Again, thank you for the time you spent on that.

**Comment by Menelion** [comment]
@TiBeN Should I also reformat the tests, or only the sources and Readme? Thanks!

**Comment by TiBeN** [comment]
You can reformat tests too

**Comment by Menelion** [comment]
Done!

**Comment by TiBeN** [comment]
Thanks man!

**Pull request merged**
